- name: Create and initialize PVCs
  kubevirt_pvc:
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name | mandatory }}"
    namespace: "{{ item.namespace | default('default') }}"
    size: "{{ item.size | default(omit) }}"
    wait: "{{ item.wait | default(false) }}"
    wait_timeout: "{{ item.wait_timeout | default(300) }}"
    labels: "{{ item.labels | default(omit) }}"
    annotations: "{{ item.annotations | default(omit) }}"
    storage_class_name: "{{ item.storage_class | default(omit) }}"
    cdi_source: "{{ lookup('template', 'templates/cdi_source.j2') | from_yaml }}"
    access_modes:
      - ReadWriteOnce
